"use client";
import { useState } from "react";
import Link from "next/link";
import { useLanguage } from "@/components/i18n/LanguageProvider";
import { LanguageSwitcher } from "@/components/i18n/LanguageSwitcher";
import { Brand } from "@/components/ui/Brand";
import { LegalLinks } from "./LegalLinks";
import { leadRepository } from "@/lib/leads/LocalLeadRepository";

type Pair = [string, string];
const privacy: { title: Pair; body: Pair }[] = [
  { title: ["What this demo is", "Qué es esta demo"], body: ["FrontDesk AI is a product demonstration for adults (18+). Miami Smile Dental and the sample leads are fictional. Use a made-up name and avoid symptoms, medical histories, insurance identifiers, payment details, or other sensitive data. This is not a patient portal.", "FrontDesk AI es una demostración para adultos (18+). Miami Smile Dental y los contactos de ejemplo son ficticios. Usa un nombre inventado y evita síntomas, historias clínicas, números de seguro, datos de pago u otros datos sensibles. No es un portal de pacientes."] },
  { title: ["Conversations and local storage", "Conversaciones y almacenamiento local"], body: ["The guided chat runs in your browser, without an external language model. Completed requests (name, contact, treatment interest, preferences, conversation and optional verification status) are saved in this browser’s local storage until you delete them. Anyone using the same browser profile can view them. They are not sent to a clinic or stored in a central lead database. Reload or close other demo tabs after deleting saved data.", "El chat guiado funciona en tu navegador, sin un modelo de lenguaje externo. Las solicitudes completas (nombre, contacto, interés, preferencias, conversación y estado opcional de verificación) se guardan en el almacenamiento local hasta que las elimines. Cualquier persona que use el mismo perfil del navegador puede verlas. No se envían a una clínica ni se guardan en una base central de contactos. Recarga o cierra otras pestañas de la demo después de borrar los datos."] },
  { title: ["Optional real verification", "Verificación real opcional"], body: ["Only if a channel is enabled and you explicitly request a code, your email or phone number is sent through our server to Resend (email) or Twilio Verify (SMS). The message contains a verification code, not your treatment interest or conversation. This permission covers the requested verification only, not advertising, clinic follow-up, or appointment confirmation. Delivery is not guaranteed. You may choose a fictional contact without requesting any message. Do not submit another person’s contact.", "Solo si el canal está habilitado y solicitas expresamente un código, tu correo o teléfono pasa por nuestro servidor a Resend (email) o Twilio Verify (SMS). El mensaje contiene un código de verificación, no tu interés en tratamientos ni tu conversación. El permiso cubre únicamente esa verificación, no publicidad, seguimiento de una clínica ni confirmación de citas. No se garantiza la entrega. Puedes elegir un contacto ficticio sin solicitar mensajes. No ingreses el contacto de otra persona."] },
  { title: ["Temporary security data and service providers", "Datos temporales de seguridad y proveedores"], body: ["When verification is enabled, Upstash Redis holds protected digests of the contact, session and IP for abuse prevention. Challenges expire after 10 minutes; rate counters expire within 24 hours. Codes are not saved in the conversation; email codes are stored only as keyed hashes. Consent version/time is included in the temporary challenge. A verified contact’s time and consent version may remain with the local lead until deletion. Vercel hosts the website and processes request metadata such as IP and user agent. Delivery and infrastructure providers may retain their own logs under their policies and account settings; deleting local demo data does not delete those logs. Processing may take place outside your country.", "Cuando se habilita la verificación, Upstash Redis guarda resúmenes protegidos del contacto, sesión e IP para prevenir abusos. Las solicitudes de código vencen a los 10 minutos y los contadores se eliminan en un máximo de 24 horas. Los códigos no se guardan en la conversación; los de email solo se almacenan como hashes con clave. La solicitud temporal incluye versión y fecha del consentimiento. El contacto local puede conservar fecha de verificación y versión de consentimiento hasta su eliminación. Vercel aloja la web y procesa metadatos como IP y navegador. Los proveedores de infraestructura y entrega pueden conservar sus propios registros según sus políticas y configuración; borrar la demo local no elimina esos registros. El procesamiento puede ocurrir fuera de tu país."] },
  { title: ["Cookies, tracking and choices", "Cookies, seguimiento y opciones"], body: ["The language preference cookie lasts up to one year. When you request verification, a necessary security cookie lasts up to 30 minutes. We have not added advertising pixels or audience analytics. We do not sell demo data or use it for targeted advertising. You can clear site cookies through your browser settings and delete locally saved requests below. Declining verification does not prevent use of the fictional demo.", "La cookie de idioma dura hasta un año. Al solicitar una verificación, una cookie de seguridad necesaria dura hasta 30 minutos. No agregamos píxeles publicitarios ni analítica de audiencia. No vendemos los datos de la demo ni los usamos para publicidad dirigida. Puedes borrar las cookies desde tu navegador y eliminar abajo las solicitudes guardadas localmente. Rechazar la verificación no impide usar la demo ficticia."] },
];
const terms: { title: Pair; body: Pair }[] = [
  { title: ["A demonstration, not a dental service", "Una demostración de producto"], body: ["This free demo illustrates a possible reception workflow for adults evaluating the product. Miami Smile Dental is fictional. No dental provider receives your request and no patient–provider relationship is created. The chat uses scripted rules and can misunderstand a question. A captured request or verified contact never means an appointment is confirmed.", "Esta demo gratuita ilustra un posible flujo de recepción para adultos que evalúan el producto. Miami Smile Dental es ficticia. Ningún profesional recibe tu solicitud ni se crea una relación con un prestador de salud. El chat usa reglas programadas y puede interpretar mal una pregunta. Una solicitud registrada o un contacto verificado nunca significa que una cita esté confirmada."] },
  { title: ["Medical questions and emergencies", "Consultas médicas y emergencias"], body: ["The demo does not diagnose, recommend treatment, establish eligibility, or provide medical advice. Contact a licensed dental professional for care. Do not rely on the chat in an emergency; call 911 in the United States or your local emergency number. Nobody monitors this demo for urgent requests.", "La demo no diagnostica, recomienda tratamientos, determina aptitud ni da asesoramiento médico. Consulta a un profesional habilitado. No dependas del chat en una emergencia: llama al 911 en Estados Unidos o al número de emergencias local. Nadie monitorea esta demo para atender urgencias."] },
  { title: ["Contact verification", "Verificación de contacto"], body: ["Real codes are optional and only available when sending services are enabled. Request codes only for an email or +1 phone number that you control. SMS message and data rates may apply; frequency depends on your requests and our limits. Stop requesting codes to stop this verification flow; no recurring marketing is scheduled. Provider-supported opt-out controls may also apply. Verification establishes access to the contact at that moment, not identity or consent to future marketing.", "Los códigos reales son opcionales y solo están disponibles al habilitar los servicios de envío. Solicita códigos únicamente para un correo o teléfono +1 que controles. Pueden aplicarse cargos por SMS y datos; la frecuencia depende de tus solicitudes y nuestros límites. Deja de pedir códigos para terminar este flujo; no se programa publicidad recurrente. También pueden aplicar las opciones de baja del proveedor. La verificación comprueba acceso al contacto en ese momento, no identidad ni consentimiento para publicidad futura."] },
  { title: ["Responsible use and availability", "Uso responsable y disponibilidad"], body: ["Do not submit patient records, misuse another person’s contact, send spam, or try to bypass delivery limits. Demo data can be reset, lost, or removed. Availability and delivery are not guaranteed. The product is not offered here as a HIPAA-compliant clinical system. Actual use by a practice requires a separate agreement, appropriate security, privacy review and any applicable business associate agreements.", "No ingreses historias clínicas, uses datos de terceros, envíes spam ni intentes evadir límites. Los datos de prueba pueden restablecerse, perderse o eliminarse. No se garantiza disponibilidad ni entrega. Aquí no se ofrece el producto como un sistema clínico conforme a HIPAA. Su uso real por una clínica requiere un acuerdo separado, seguridad adecuada, revisión de privacidad y los acuerdos de asociado comercial que correspondan."] },
  { title: ["Commercial terms and third-party names", "Condiciones comerciales y marcas"], body: ["Exploring this demo creates no subscription or payment obligation. Any Founding Practice offer, setup fee, monthly fee, scope, cancellation or refund terms must be agreed in a separate written proposal before purchase. Treatment and provider names belong to their respective owners; their mention does not imply sponsorship or endorsement. Nothing here limits rights that cannot legally be waived.", "Explorar la demo no crea una suscripción ni obligación de pago. Cualquier oferta Founding Practice, cargo inicial, mensualidad, alcance, cancelación o devolución debe acordarse por escrito antes de comprar. Los nombres de tratamientos y proveedores pertenecen a sus titulares; mencionarlos no implica patrocinio ni respaldo. Este texto no limita derechos irrenunciables por ley."] },
];
const accessibility: { title: Pair; body: Pair }[] = [
  { title: ["Designed to be usable", "Diseñada para ser accesible"], body: ["The demo supports keyboard navigation, visible focus, labeled inputs, English and Spanish, and responsive layouts. The scroll illustration has a static version on small screens and when your device requests reduced motion. It does not require dragging or precise mouse gestures.", "La demo permite navegación por teclado, foco visible, campos etiquetados, inglés y español, y diseños adaptables. La ilustración al desplazarse tiene una versión estática en pantallas pequeñas y cuando tu dispositivo pide reducir movimiento. No requiere arrastrar ni hacer gestos precisos con el mouse."] },
  { title: ["Ongoing improvements", "Mejora continua"], body: ["We aim to follow WCAG 2.2 AA guidance. This is a design target, not a claim of a completed independent accessibility audit. If you encounter a barrier, describe the page, browser and assistive technology when contacting the operator listed below. Do not include health information in a report.", "Buscamos seguir las pautas WCAG 2.2 AA. Es un objetivo de diseño, no una afirmación de auditoría independiente completada. Si encuentras una barrera, indica la página, navegador y tecnología de asistencia al contactar al responsable indicado abajo. No incluyas información de salud en el reporte."] },
];

export function LegalPage({ kind, identity, availability }: { kind: "privacy" | "terms" | "accessibility"; identity: { name: string; country: string; email: string }; availability: { email: boolean; sms: boolean } }) {
  const { t } = useLanguage();
  const [confirmDelete, setConfirmDelete] = useState(false);
  const [deleted, setDeleted] = useState(false);
  const [error, setError] = useState(false);
  const titles = { privacy: t("Privacy & your data", "Privacidad y tus datos"), terms: t("Terms for this demo", "Términos de esta demo"), accessibility: t("An open door for everyone.", "Una puerta abierta para todos.") };
  const sections = { privacy, terms, accessibility }[kind];
  async function remove() { try { await leadRepository.clearDemo(); setDeleted(true); setConfirmDelete(false); setError(false); } catch { setError(true); } }
  return <div className="min-h-screen bg-paper">
    <header className="page-shell flex flex-wrap items-center justify-between gap-3 py-5"><Brand /><LanguageSwitcher /></header>
    <main id="main" className="mx-auto max-w-3xl px-5 py-12 sm:px-8">
      <Link href="/" className="text-sm text-teal underline underline-offset-4">← {t("Back to FrontDesk AI", "Volver a FrontDesk AI")}</Link>
      <p className="eyebrow mt-10">FrontDesk AI · Demo</p><h1 className="mt-4 text-4xl leading-tight sm:text-5xl">{titles[kind]}</h1>
      <p className="mt-4 text-xs text-ink-soft">{t("Updated September 25, 2026", "Actualizado el 25 de septiembre de 2026")}</p>
      <div className="mt-7 rounded-2xl border border-line bg-white p-5 text-sm leading-6 text-ink-soft">
        <p className="font-semibold text-ink">{t("Current sending status", "Estado actual de envíos")}</p>
        <p>Email: {availability.email ? t("enabled", "habilitado") : t("disabled", "deshabilitado")} · SMS: {availability.sms ? t("enabled", "habilitado") : t("disabled", "deshabilitado")}.</p>
        {!identity.name || !identity.country || !identity.email ? <p className="mt-2">{t("Operator identity and privacy contact are being completed. Real verification stays disabled until those details and the sending services are configured. Use fictional details only.", "La identidad del responsable y el contacto de privacidad están pendientes de completar. La verificación real permanece deshabilitada hasta configurar esos datos y los servicios de envío. Usa solo datos ficticios.")}</p> : <p className="mt-2">{identity.name} · {identity.country}<br /><a className="text-teal underline" href={`mailto:${identity.email}`}>{identity.email}</a></p>}
      </div>
      {sections.map(section => <section key={section.title[0]} className="mt-9"><h2 className="text-2xl">{t(...section.title)}</h2><p className="mt-3 text-sm leading-7 text-ink-soft">{t(...section.body)}</p></section>)}
      {kind === "privacy" && <>
        <section className="mt-9 rounded-2xl border border-line bg-white p-5"><h2 className="text-2xl">{t("Delete your local demo data", "Borra los datos locales de la demo")}</h2><p className="mt-3 text-sm leading-6 text-ink-soft">{t("Remove all requests saved by this demo in this browser, including fictional examples. This cannot be undone. It does not clear other websites, your language choice or provider logs.", "Elimina todas las solicitudes guardadas por esta demo en este navegador, incluidos los ejemplos ficticios. No se puede deshacer. No borra otros sitios, tu idioma ni registros de los proveedores.")}</p>
          {deleted ? <p role="status" className="mt-4 text-sm text-teal">{t("Saved requests deleted. Reload other open demo tabs.", "Solicitudes guardadas eliminadas. Recarga otras pestañas abiertas de la demo.")}</p> : confirmDelete ? <div className="mt-4 flex flex-wrap gap-3"><button className="button-primary" onClick={() => void remove()}>{t("Yes, delete saved requests", "Sí, borrar solicitudes")}</button><button className="button-secondary" onClick={() => setConfirmDelete(false)}>{t("Cancel", "Cancelar")}</button></div> : <button className="button-secondary mt-4" onClick={() => setConfirmDelete(true)}>{t("Delete local demo data", "Borrar datos locales")}</button>}
          {error && <p role="alert" className="mt-3 text-sm text-coral">{t("Could not clear storage. Try again or use your browser’s site-data settings.", "No se pudo borrar el almacenamiento. Reintenta o usa la configuración de datos del navegador.")}</p>}
        </section>
        <section className="mt-9"><h2 className="text-2xl">{t("Requests and provider policies", "Solicitudes y políticas de proveedores")}</h2><p className="mt-3 text-sm leading-7 text-ink-soft">{t("Where applicable, request access, correction, deletion or other privacy rights through the operator contact above. Rights depend on your location and applicable law. Do not send sensitive information. Service-provider policies:", "Cuando corresponda, solicita acceso, corrección, eliminación u otros derechos de privacidad mediante el contacto del responsable indicado arriba. Los derechos dependen de tu ubicación y la ley aplicable. No envíes información sensible. Políticas de proveedores:")}</p><div className="mt-3 flex flex-wrap gap-4 text-sm text-teal underline"><a href="https://vercel.com/legal/privacy-policy">Vercel</a><a href="https://resend.com/legal/privacy-policy">Resend</a><a href="https://www.twilio.com/en-us/legal/privacy">Twilio</a><a href="https://upstash.com/trust/privacy.pdf">Upstash</a></div></section>
      </>}
    </main><footer className="border-t border-line py-8"><LegalLinks /></footer>
  </div>;
}
